"""texts

Revision ID: 23715de7a00c
Revises: 
Create Date: 2026-08-16 01:03:35.488935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23715de7a00c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='seed', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('length', sa.Integer(), sa.Computed('char_length(content)', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lang in ('ru','en')", name='ck_texts_lang'),
    sa.CheckConstraint('char_length(content) > 0', name='ck_texts_content_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_texts_lang_length', 'texts', ['lang', 'length'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_texts_lang_length', table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###
