services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: typing
      POSTGRES_PASSWORD: typing
      POSTGRES_DB: typing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U typing" ]
        interval: 5s
        timeout: 3s
        retries: 10

volumes:
  pgdata: